<?php 
$users = $viewData['users'];
?>
<h1 class="page-header">Template</h1>

<a href="/timeline/insert">Insert</a>
<div class="table-responsive">
<table class="table table-striped">
   
    <?php foreach($users as $id => $user):?>
        <tr>
           <?php 
            //$user = explode(",", $user);
          
            foreach ($user as $value):?>               
                 
                <td><?php echo $value ;?></td>
            <?php endforeach; ?>
            <td>
                <a href="/timeline/update/id/<?=$user['stardate'];?>">Update</a> | 
                <a href="/timeline/delete/id/<?=$user['stardate'];?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
</div>